version: '3'

services:
  keycloak:
      image: jboss/keycloak:latest
      container_name: keycloak
      hostname: keycloak
      restart: unless-stopped
      networks:
       - atlassiannet
      volumes:
       - keycloak:/tmp/realms
      environment:
       - DB_VENDOR=POSTGRES
       - DB_ADDR=postgres_atlassian
       - DB_DATABASE=keycloakdb
       - DB_USER=keycloakdbuser
       - DB_PASSWORD=Jiaia921843kfaHWy
       - KEYCLOAK_USER=admin
       - KEYCLOAK_PASSWORD=admin
      ports:
       - 8080:8080

  postgres_atlassian:
    image: postgres
    container_name: postgres_atlassian
    hostname: postgres_atlassian
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - postgres_atlassian: /var/lib/postgresql/data 
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=QksuYejx_speI93'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

volumes:
  keycloak:
    external: true
  postgres_atlassian:
    external: true

networks:
  atlassiannet:
    external:
      name: network-atlassian