version: '3'

services:
  bitbucket:
    image: cptactionhank/atlassian-bitbucket
    container_name: bitbucket
    hostname: bitbucket
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - bitbucketdata:/var/atlassian/bitbucket
    ports:
      - '7990:7990'
    environment:
      - 'CATALINA_OPTS= -Xms2g -Xmx3g'
      - 'JVM_MINIMUM_MEMORY=2g'
      - 'JVM_MAXIMUM_MEMORY=3g'
      - 'DOCKER_WAIT_HOST=postgres_atlassian'
      - 'DOCKER_WAIT_PORT=5432'
      - 'BITBUCKET_EMBEDDED_SEARCH=true'

  keycloak:
      image: jboss/keycloak:latest
      container_name: keycloak
      hostname: keycloak
      restart: unless-stopped
      networks:
       - atlassiannet
      volumes:
       - keycloak:/tmp/realms
      environment:
       - DB_VENDOR=POSTGRES
       - DB_ADDR=postgres_atlassian
       - DB_DATABASE=keycloakdb
       - DB_USER=keycloakdbuser
       - DB_PASSWORD=Jiaia921843kfaHWy
       - KEYCLOAK_USER=admin
       - KEYCLOAK_PASSWORD=admin
      ports:
       - 8080:8080

  postgres_atlassian:
    image: postgres
    container_name: postgres_atlassian
    hostname: postgres_atlassian
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - postgres_atlassian:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=QksuYejx_speI93'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

volumes:
  bitbucketdata:
    external: true
  keycloak:
    external: true
  postgres_atlassian:
    external: true
  apereo-cas:
    external: true  

networks:
  atlassiannet:
    external:
      name: network-atlassian