version: '3'

services:
  jira:
    image: cptactionhank/atlassian-jira-software:8.12.3
    container_name: jira
    hostname: jira
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - jira_soft_var:/var/atlassian/jira
      - jira_soft_opt:/opt/atlassian/jira
      - jira_soft_logs:/opt/atlassian/jira/logs
      - jira_soft_certs/:/etc/ssl/certs/java/
    ports:
      - '8085:8080'

  postgres_atlassian:
    image: postgres
    container_name: postgres_atlassian
    hostname: postgres_atlassian
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - postgres_atlassian:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=QksuYejx_speI93'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

volumes:
  jira_soft_var:
    external: true
  jira_soft_opt:
    external: true
  jira_soft_logs:
    external: true
  jira_soft_certs:
    external: true
  keycloak:
    external: true
  postgres_atlassian:
    external: true

networks:
  atlassiannet:
    external:
      name: network-atlassian