version: '3'

services:
  jira:
    image: cptactionhank/atlassian-jira-software
    container_name: jira
    hostname: jira
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - jira_soft_var:/var/atlassian/jira
      - jira_soft_opt:/opt/atlassian/jira
      - jira_soft_logs:/opt/atlassian/jira/logs
    ports:
      - '8085:8080'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  keycloak:
      image: jboss/keycloak:latest
      container_name: keycloak
      hostname: keycloak
      restart: unless-stopped
      networks:
       - atlassiannet
      volumes:
       - keycloak:/tmp/realms
      environment:
       - DB_VENDOR=POSTGRES
       - DB_ADDR=postgre_atlassian
       - DB_DATABASE=keycloakdb
       - DB_USER=keycloakdbuser
       - DB_PASSWORD=Jiaia921843kfaHWy
       - KEYCLOAK_USER=admin
       - KEYCLOAK_PASSWORD=admin
      ports:
       - 8080:8080

  postgre_atlassian:
    image: blacklabelops/postgres
    container_name: postgre_atlassian
    hostname: postgre_atlassian
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - postgre_atlassian:/var/lib/postgresql
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=QksuYejx_speI93'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    labels:
      com.blacklabelops.description: "Postgre Atlassian Database Server"
      com.blacklabelops.service: "postgre_atlassian"

volumes:
  jira_soft_var:
    external: true
  jira_soft_opt:
    external: true
  jira_soft_logs:
    external: true
  keycloak:
    external: true
  postgre_atlassian:
    external: true

networks:
  atlassiannet:
    external:
      name: network-atlassian