version: '3'

services:
  confluence:
    image: cptactionhank/atlassian-confluence
    container_name: confluence
    hostname: confluence
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - confluence_var:/var/atlassian/confluence/
      - confluence_opt/:/opt/atlassian/confluence/
      - confluence_logs/:/opt/atlassian/confluence/logs
    ports:
      - '8090:8090'

volumes:
  confluence_var:
    external: true
  confluence_opt:
    external: true
  confluence_logs:
    external: true

networks:
  atlassiannet:
    external:
      name: network-atlassian