version: '3'

services:
  nginx:
    image: 'blacklabelops/nginx'
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      - atlassiannet
    environment:
      - 'REVERSE_PROXY_BUFFERING='
      - 'REVERSE_PROXY_BUFFERS='
      - 'REVERSE_PROXY_BUFFERS_SIZE='

      - 'SERVER1SERVER_NAME=confluence.nesski.com'
      - 'SERVER1REVERSE_PROXY_LOCATION1=/'
      - 'SERVER1REVERSE_PROXY_PASS1=http://confluence:8090'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - nginxdata:/etc/nginx
      - nginxdata:/home/nginx
      - nginxwww:/var/lib/nginx/html
      - nginxdata:/var/log/nginx

volumes:
  nginxdata:
    external: true
  nginxwww:
    external: true

networks:
  atlassiannet:
    external:
      name: network-atlassian