version: '3'

services:
  jira:
    #depends_on:
    #  - postgre_atlassian
    image: cptactionhank/atlassian-jira
    container_name: jira
    hostname: jira
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - jira_var:/var/atlassian/jira
      - jira_opt:/opt/atlassian/jira
      - jira_logs:/opt/atlassian/jira/logs
    ports:
      - '8095:8080'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

volumes:
  jira_var:
    external: true
  jira_opt:
    external: true
  jira_logs:
    external: true

networks:
  atlassiannet:
    external:
      name: network-atlassian